spring:
  datasource:
    url: jdbc:mysql://localhost:33308/notification?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

outbox:
  batch: 50

notification:
  http:
    dummy: true
    base-url: https://postman-echo.com
    connect-timeout-ms: 2000
    response-timeout-ms: 3000
    read-timeout-ms: 3000
    write-timeout-ms: 3000
    max-in-memory-size: 1MB
  async:
    pool:
      core: 8
      max: 32
      queue: 1000
      keep-alive-seconds: 60

logging:
  level:
    com.github.shyiko: INFO
    com.example.cdc: DEBUG
