spring:
  datasource:
    url: jdbc:mysql://localhost:33308/notification?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

outbox:
  batch: 200

logging:
  level:
    com.github.shyiko: INFO
    com.example.cdc: DEBUG
