version: "3.9"
services:
  mysql:
    image: mysql:8.4
    container_name: notification-mysql
    ports:
      - "33308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notification
      TZ: Asia/Seoul
