version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: outbox-mysql
    ports:
      - "33308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notification
      TZ: Asia/Seoul
