spring:
  datasource:
    url: jdbc:mysql://localhost:33306/notification?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: password
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.github.shyiko: INFO
    com.example.cdc: DEBUG

cdc:
  host: localhost
  port: 33306
  username: root
  password: password
  schema: notification
  includeTable: outbox_event
  serverId: 5401
  connectTimeoutMs: 10000
  reconnectDelayMs: 3000

  queueCapacity: 10000
  offerTimeoutMs: 200

  gtidSet:
  binlogFilename:
  binlogPosition:

  consumeBatchSize: 200
  consumeFixedDelayMs: 1000
