spring:
  datasource:
    url: jdbc:mysql://localhost:33307/shorturl?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: password
  jpa:
    open-in-view: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.github.shyiko: INFO
    com.example.cdc: DEBUG
